### ISSUE TITLE
[PE-D][Tester B] Add command allows non numeric characters for phone number

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103-W14-3/tp#170] opened 2023-11-03 20:33 UTC
![image.png](https://raw.githubusercontent.com/nicholascher/ped/main/files/13ea2e42-f775-4d70-aa41-e829e1d87364.png)

The add command allows non numeric characthers entered for the phone number.

**Command Used**: add n/Test2 p/123/// e/test@gmail.com

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: nicholascher/ped#8

**Comment by Cloud7050** [comment] 2023-11-04 00:07
Duplicate of #166.

**Closed** 2023-11-04 00:07 UTC
Labels: duplicate
